In [1]:
##Link to dataset on website
##https://data.wprdc.org/dataset/city-of-pittsburgh-courts/resource/a5b71bfa-840c-4c86-8f43-07a9ae854227

##Imports
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

courtsData = pd.read_csv("courts_and_rinks.csv")
##This is what the data looks like
courtsData.head(10)

,id,name,type,park,location,surface_material,grandstand,inactive,neighborhood,council_district,ward,tract,public_works_division,pli_division,police_zone,fire_zone,latitude,longitude
0,1592343416,Allegheny Commons Basketball Court 1,Basketball (Full),Allegheny Commons,NaN,NaN,0,f,Allegheny Center,1,22,42003562700,1,22,1,1-7,40.454443,-80.008104
1,1365248699,Allegheny Commons Park Tennis Court 1,Tennis,Allegheny Commons,NaN,Asphalt,0,f,Allegheny Center,1,22,42003562700,1,22,1,1-7,40.452400,-80.012531
2,1757180821,Allegheny Commons Park Tennis Court 2,Tennis,Allegheny Commons,NaN,Asphalt,0,f,Allegheny Center,1,22,42003562700,1,22,1,1-7,40.452238,-80.012150
3,744303307,Allegheny Commons Park Tennis Court 3,Tennis,Allegheny Commons,NaN,Asphalt,0,f,Allegheny Center,1,22,42003562700,1,22,1,1-7,40.452075,-80.011767
4,1157777481,Alton Park Basketball Court 1,Basketball (Half),Alton Park,NaN,Asphalt,0,f,Beechview,4,19,42003191600,5,19,6,4-28,40.414152,-80.022305
5,299909706,Alton Park Basketball Court 2,Basketball (Full),Alton Park,NaN,Asphalt,0,f,Beechview,4,19,42003191600,5,19,6,4-28,40.414155,-80.022088
6,912994212,Ammon Park Basketball Court 1,Basketball (Full),Ammon Park,NaN,Asphalt,0,f,Bedford Dwellings,6,5,42003050900,3,5,2,2-5,40.449331,-79.977473
7,1342647628,Ammon Park Basketball Court 2,Basketball (Full),Ammon Park,NaN,Asphalt,0,f,Bedford Dwellings,6,5,42003050900,3,5,2,2-5,40.449184,-79.977371
8,470473315,Arlington Park Basketball Court 1,Basketball (Full),Arlington Park,NaN,Asphalt,0,f,South Side Slopes,3,16,42003160800,3,16,3,4-22,40.417990,-79.975053
9,229834077,Armstrong Park Basketball Court 1,Basketball (Full),Armstrong Park,NaN,Asphalt,0,f,South Side Flats,3,17,42003170200,3,17,3,4-24,40.427925,-79.986011

In [3]:
#Groups each court or rink by which neighborhood it is found in. Disregards the type and just adds them all up
courtsGroup=courtsData.groupby("neighborhood").count()
#Drops all 'unnecessary' columns. Setting the data to a new variable
courtsSlim=courtsGroup.drop(columns=['park','name','id','location','surface_material','grandstand','inactive','council_district','ward','tract','public_works_division','pli_division','police_zone', 'fire_zone', 'latitude','longitude'])
courtsSlim.head(50)

                          type
neighborhood
Allegheny Center             9
Allentown                    1
Banksville                   3
Bedford Dwellings            2
Beechview                    7
Beltzhoover                  9
Bloomfield                   5
Bon Air                      1
Brighton Heights             2
Brookline                    9
Carrick                      3
Central Lawrenceville        1
Central Northside            2
Central Oakland              1
Crafton Heights              3
Crawford-Roberts             2
Duquesne Heights             2
East Carnegie                2
East Hills                   2
East Liberty                 6
Elliott                      5
Fairywood                    2
Fineview                     2
Garfield                     3
Greenfield                   5
Hays                         1
Hazelwood                   10
Highland Park               20
Homewood West                1
Larimer                      1
Lincoln Place                4
Lincoln-Lemington-Belmar     2
Lower Lawrenceville          6
Manchester                   6
Marshall-Shadeland           1
Middle Hill                  1
Morningside                  4
Mount Washington             5
New Homestead                2
Oakwood                      3
Perry North                  2
Perry South                  1
Point Breeze                 2
Point Breeze North           1
Polish Hill                  1
Regent Square                6
Shadyside                    2
Sheraden                     6
South Oakland                2
South Side Flats             5

In [4]:
#Remove all neighborhoods with 2 or less in the quantity section
courtsFinal=courtsSlim.query('type>1')
courtsFinal.head(50)

                          type
neighborhood
Allegheny Center             9
Banksville                   3
Bedford Dwellings            2
Beechview                    7
Beltzhoover                  9
Bloomfield                   5
Brighton Heights             2
Brookline                    9
Carrick                      3
Central Northside            2
Crafton Heights              3
Crawford-Roberts             2
Duquesne Heights             2
East Carnegie                2
East Hills                   2
East Liberty                 6
Elliott                      5
Fairywood                    2
Fineview                     2
Garfield                     3
Greenfield                   5
Hazelwood                   10
Highland Park               20
Lincoln Place                4
Lincoln-Lemington-Belmar     2
Lower Lawrenceville          6
Manchester                   6
Morningside                  4
Mount Washington             5
New Homestead                2
Oakwood                      3
Perry North                  2
Point Breeze                 2
Regent Square                6
Shadyside                    2
Sheraden                     6
South Oakland                2
South Side Flats             5
South Side Slopes            6
Spring Garden                2
Spring Hill-City View        4
Squirrel Hill South         26
Stanton Heights              2
Swisshelm Park               2
Terrace Village              5
Troy Hill                    8
Upper Lawrenceville          2
West End                     2

In [3]:
##courtsFinal.plot.bar()

In [5]:
##Seperate the neighborhoods by number of courts. Points are given for the number of courts or rinks in the neighborhood
##5 points are given to any neighborhood with more than 20 courts/rinks
courts5 = courtsFinal[courtsFinal['type']>19]
fullcourts5 = courts5.assign(score=5)
print(fullcourts5)

                     type  score
neighborhood
Highland Park          20      5
Squirrel Hill South    26      5

In [6]:
##4 points are given to any neighborhood with 10 or more and less than 20 courts/rinks
courts4 = courtsFinal[(courtsFinal['type']>9) & (courtsFinal['type']<20)]
fullcourts4 = courts4.assign(score=4)
print(fullcourts4)

              type  score
neighborhood
Hazelwood       10      4

In [7]:
##3 points are given to any neighborhood with 7 or more and less than 10 courts/rinks
courts3 = courtsFinal[(courtsFinal['type']>7) & (courtsFinal['type']<10)]
fullcourts3 = courts3.assign(score=3)
print(fullcourts3)

                  type  score
neighborhood
Allegheny Center     9      3
Beltzhoover          9      3
Brookline            9      3
Troy Hill            8      3

In [8]:
##2 points are given to any neighborhood with 5 or more and less than 7 courts/rinks
courts2 = courtsFinal[(courtsFinal['type']>4) & (courtsFinal['type']<8)]
fullcourts2 = courts2.assign(score=2)
print(fullcourts2)

                     type  score
neighborhood
Beechview               7      2
Bloomfield              5      2
East Liberty            6      2
Elliott                 5      2
Greenfield              5      2
Lower Lawrenceville     6      2
Manchester              6      2
Mount Washington        5      2
Regent Square           6      2
Sheraden                6      2
South Side Flats        5      2
South Side Slopes       6      2
Terrace Village         5      2

In [9]:
##1 point is given to any neighborhood with 3 or more and less than 5 courts/rinks
courts1 = courtsFinal[(courtsFinal['type']>1) & (courtsFinal['type']<5)]
fullcourts1 = courts1.assign(score=1)
print(fullcourts1)

                          type  score
neighborhood
Banksville                   3      1
Bedford Dwellings            2      1
Brighton Heights             2      1
Carrick                      3      1
Central Northside            2      1
Crafton Heights              3      1
Crawford-Roberts             2      1
Duquesne Heights             2      1
East Carnegie                2      1
East Hills                   2      1
Fairywood                    2      1
Fineview                     2      1
Garfield                     3      1
Lincoln Place                4      1
Lincoln-Lemington-Belmar     2      1
Morningside                  4      1
New Homestead                2      1
Oakwood                      3      1
Perry North                  2      1
Point Breeze                 2      1
Shadyside                    2      1
South Oakland                2      1
Spring Garden                2      1
Spring Hill-City View        4      1
Stanton Heights              2      1
Swisshelm Park               2      1
Upper Lawrenceville          2      1
West End                     2      1